version: '3.8'
services:

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

#   version: '3.8'
# services:

#   postgres-db:
#     image: postgres:latest
#     container_name: postgres-db
#     command: ~/util/create_cert.sh
#     ports:
#       - "5432:5432"
#     environment:
#       - POSTGRES_DB=mydatabase
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=password
#     volumes:
#       - ./postgres-certs/:/var/lib/postgresql/certs/
#       - ./postgres-data:/var/lib/postgresql/data
#       - ./postgres-initdb:/docker-entrypoint-initdb.d/
#       - ./util/db_entrypoint.sh:/usr/local/bin/db_entrypoint.sh
#     entrypoint: ["/usr/local/bin/db_entrypoint.sh"]
# volumes:
#   postgres-data: