name: Pulumi
on:
  push:
    branches:
      - main
jobs:
  up:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.5.0
        with:
          node-version-file: package.json
      - uses: pulumi/actions@v4
        with:
          command: refresh
          work-dir: pulumi
          stack-name: fosforescent/fos-base/base
          # upsert: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - uses: pulumi/actions@v4
        with:
          command: up
          work-dir: pulumi
          stack-name: fosforescent/fos-base/base
          # upsert: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}