name: PR Plan

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  plan-cluster:
    uses: ./.github/workflows/tf_plan_step.yml
    name: Create terraform plan for cluster
    with: 
      step-path: 'kube-cluster'
    secrets:
      DOTENV: ${{ secrets.DOTENV }}
      BACKEND_CONFIG: ${{ secrets.BACKEND_CONFIG }}
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}


  plan-kube-network:
    if: needs.plan-cluster.outputs.changes != '1' 
    uses: ./.github/workflows/tf_plan_step.yml
    name: Create terraform plan for kube network
    needs: [plan-cluster]
    with: 
      step-path: 'kube-network'
    secrets:
      DOTENV: ${{ secrets.DOTENV }}
      BACKEND_CONFIG: ${{ secrets.BACKEND_CONFIG }}
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    

  plan-helm-apps:
    if: needs.plan-kube-network.outputs.changes != '1' 
    uses: ./.github/workflows/tf_plan_step.yml
    name: Create terraform plan for helm apps
    needs: [plan-kube-network]
    with: 
      step-path: 'helm-apps'
    secrets:
      DOTENV: ${{ secrets.DOTENV }}
      BACKEND_CONFIG: ${{ secrets.BACKEND_CONFIG }}
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}


  plan-argo-apps:
    uses: ./.github/workflows/tf_plan_step.yml
    if: needs.plan-helm-apps.outputs.changes != '1'
    with: 
      step-path: 'argo-apps'
    secrets:
      DOTENV: ${{ secrets.DOTENV }}
      BACKEND_CONFIG: ${{ secrets.BACKEND_CONFIG }}
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    name: Create terraform plan
    needs: [plan-helm-apps]
